### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by mightymarcus** [ncannasse/heaps#125] opened 2015-10-30 05:07 UTC
Hi. I don't know if this is a real issue, i just wanted to check out your framework, but almost no sample is working.

There are different errors, but the most frequently is this:

heaps/git/hxsl/AgalOut.hx:29: characters 12-36 : { t : format.agal.RegType, swiz : format.agal.Swizzle, index : Int, access : Null<{ t : format.agal.RegType, offset : Int, comp : format.agal.C }> } cannot be constructed

And in the webgl target:

Uncaught Error: Unexpected helper function in linker getPosition

**Comment by ncannasse** [comment] 2015-10-30 08:28
For AGAL you need to update to latest format library, I've just pushed an update.
For WebGL, it's a duplicate of #115

**Closed by ncannasse** 2015-10-30 08:28 UTC
